### ISSUE TITLE
Error startup

### ISSUE THREAD

**Issue by SergeyDjam** [thetawavegame/thetawave#176] opened 2024-04-22 09:08 UTC
v0.2.0 tar.gz
rustc 1.77.2

cargo build --release 
or 
cargo build --release --features storage

```
./thetawave
2024-04-22T09:03:55.509218Z  INFO bevy_winit::system: Creating new window "Thetawave" (0v1)
2024-04-22T09:03:55.509581Z  INFO log: Guessed window scale factor: 1.3333333333333333    
2024-04-22T09:03:55.599143Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel(R) UHD Graphics 620 (KBL GT2)", vendor: 32902, device: 22807, device_type: IntegratedGpu, driver: "Intel open-source Mesa driver", driver_info: "Mesa 20.1.10", backend: Vulkan }
2024-04-22T09:03:55.694549Z  WARN bevy_rapier2d::plugin::plugin: TimestepMode is set to `Variable { max_dt: 0.016666668, time_scale: 1.0, substeps: 1 }`, it is recommended to use `TimestepMode::Fixed` if you have the physics in `FixedUpdate`
2024-04-22T09:03:55.747008Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux 2016.1 ROSA Desktop Fresh R11.1", kernel: "5.13.9-generic-1rosa-x86_64", cpu: "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz", core_count: "4", memory: "30.7 GiB" }
2024-04-22T09:03:55.907767Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/thetawave_logo_spritesheet.png
2024-04-22T09:03:55.907896Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/megablast_ability.png
2024-04-22T09:03:55.907915Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/menu_button_spritesheet.png
2024-04-22T09:03:55.907925Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/charge_ability.png
2024-04-22T09:03:55.908392Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/warning_gradient.png
2024-04-22T09:03:55.908427Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/defense_gradient.png
2024-04-22T09:03:55.908438Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/bullet_ability.png
2024-04-22T09:03:55.908447Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/ability_square_left.png
2024-04-22T09:03:55.908455Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/ability_square_right.png
2024-04-22T09:03:55.908466Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/blast_ability.png
2024-04-22T09:03:55.909291Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/sounds/objective_completed.wav
2024-04-22T09:03:55.909369Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/sounds/button_select_1.wav
2024-04-22T09:03:55.909393Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/item_placeholder.png
2024-04-22T09:03:55.909408Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/sounds/button_select_2.wav
2024-04-22T09:03:55.910016Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/sounds/button_release_1.wav
2024-04-22T09:03:55.910048Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/sounds/button_release_2.wav
2024-04-22T09:03:55.910236Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/sounds/button_release_3.wav
2024-04-22T09:03:55.910366Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/sounds/button_confirm.wav
2024-04-22T09:03:55.910513Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/tutorial_drone_spritesheet.png
2024-04-22T09:03:55.912687Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/crustling_tentacle_1.png
2024-04-22T09:03:55.912775Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/crustling_spritesheet.png
2024-04-22T09:03:55.912855Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/crustling_tentacle_2.png
2024-04-22T09:03:55.912856Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/sounds/button_select_3.wav
2024-04-22T09:03:55.912878Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/crustling_tentacle_3.png
2024-04-22T09:03:55.912890Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/sounds/button_select_4.wav
2024-04-22T09:03:55.912909Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/repeater_head_spritesheet.png
2024-04-22T09:03:55.912910Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/sounds/button_select_5.wav
2024-04-22T09:03:55.912920Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/repeater_body_spritesheet.png
2024-04-22T09:03:55.912927Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/repeater_right_shoulder_spritesheet.png
2024-04-22T09:03:55.913484Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/repeater_left_shoulder_spritesheet.png
2024-04-22T09:03:55.913580Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/repeater_right_arm_spritesheet.png
2024-04-22T09:03:55.913693Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/repeater_right_claw_spritesheet.png
2024-04-22T09:03:55.913709Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/repeater_left_arm_spritesheet.png
2024-04-22T09:03:55.913722Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/repeater_left_claw_spritesheet.png
2024-04-22T09:03:55.913523Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/juggernaut_character_outline.png
2024-04-22T09:03:55.914287Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/gain_projectiles_spritesheet.png
2024-04-22T09:03:55.914765Z ERROR bevy_asset::server: Path not found: /var/disk/admin/rpmbuild/BUILD/thetawave-0.2.0/target/release/assets/texture/juggernaut_character.png
2024-04-22T09:03:55.921179Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:55.923460Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:55.930808Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:55.930861Z  INFO log: ignoring unknown chunk: tag=bext, len=604.    
2024-04-22T09:03:55.931257Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:55.932606Z  INFO log: found the format marker [ff, fb] @ 0+2 bytes.    
2024-04-22T09:03:55.932637Z  INFO log: using xing header for duration    
2024-04-22T09:03:55.933577Z  INFO log: found the format marker [ff, fb] @ 0+2 bytes.    
2024-04-22T09:03:55.933618Z  INFO log: using xing header for duration    
2024-04-22T09:03:56.235442Z  INFO log: found the format marker [ff, fb] @ 0+2 bytes.    
2024-04-22T09:03:56.235555Z  INFO log: using xing header for duration    
2024-04-22T09:03:56.349148Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:56.349335Z  INFO log: found the format marker [ff, fb] @ 0+2 bytes.    
2024-04-22T09:03:56.349353Z  INFO log: using xing header for duration    
2024-04-22T09:03:56.369499Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:56.369660Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:56.370665Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:56.376591Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:56.377073Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:56.377567Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:56.377587Z  INFO log: ignoring unknown chunk: tag=bext, len=603.    
2024-04-22T09:03:56.379975Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:56.380913Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:56.382361Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:56.382754Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:03:56.383207Z  INFO log: found the format marker [52, 49, 46, 46] @ 0+2 bytes.    
2024-04-22T09:04:25.591820Z  INFO bevy_window::system: No windows are open, exiting
2024-04-22T09:04:25.592420Z  INFO bevy_winit::system: Closing window 0v1

```

**Comment by cdsupina** [comment] 2024-04-22 14:49
The issue is that you do not have the assets. We store them on AWS. Please read the "Assets" section of the contributing guide and message me back here after you have completed steps 0 and 1.

https://github.com/thetawavegame/thetawave/blob/main/CONTRIBUTING.md

**Comment by SergeyDjam** [comment] 2024-04-22 15:21
But I wanted to play the game offline

**Comment by cdsupina** [comment] 2024-04-22 17:37
Maybe @varoonp123 should explain

**Comment by varoonp123** [comment] 2024-04-22 21:15
We store binary assets such as audio files and larger images outside of git because git is meant for tracking diffs in text. I added a [note in the README](https://github.com/thetawavegame/thetawave/blob/0eeed758b973d2ca5b285d07b77f865c19b9aa2f/README.md#building-and-playing-locally) about playing directly from a Github release, or downloading the assets from a github release.

**Comment by varoonp123** [comment] 2024-04-22 22:54
@SergeyDjam can you try running after downloading the assets from our release tarball, by executing the following command from the repo root:

```bash

curl -Ls https://github.com/thetawavegame/thetawave/releases/download/v0.2.0/thetawave-0.2.0-x86_64-unknown-linux-gnu.tar.gz  \
    | tar -xz -C assets/ --strip-components=2 --wildcards "*/assets/*"
```

**Comment by vitali2y** [comment] 2024-04-23 20:38
Above `curl` for downloading the assets helped to run game smoothly.

**Comment by cdsupina** [comment] 2024-04-24 22:26
@SergeyDjam Did the curl command work for you? We can close the issue if you are able to build the game.

**Comment by dh337071** [comment] 2024-04-27 22:33
I couldn't get the curl command to work but I was able to download the assets by following the link.

**Closed as completed** 2024-10-21 14:23 UTC
